README.md, update_markdown_chapter_references.rb
New script for updating chapter references (and the TOC) in a collection of Markdown-formatted chapters (documents).
=> New script for updating chapter/TOC references in markdown documents

update_markdown_chapter_references.rb
Add insertion functionality, and made several refactorings/fixes.
=> Update markdown: insertion functionality

github_create.rb
Improvements:
- better/correct error handling
- review request functionality
- status messages
=> Improvements to github_create.pr

README.md, ownsync
Convenient little script, whose interesting part is the poor man's configfile parsing.
=> Add ownsync

install_btrfs_checker, install_smart_notifier
- enforce running with admin permissions
- add remaining missing ownership changes
=> Checker scripts: ownership improvements/fixes

CHANGELOG.md, Gemfile, downer
Add `downer` Ruby script, for downloading and automatically installing packages/images.
=> Add `downer` Ruby script

prettify
Add force format functionality, for files whose extension is not descriptive of the format.
Done minor refactorings, and added long help.
=> prettify: add force format functionality, and various improvements

Gemfile, README.md, mk_invoice, mk_invoice_template/[Content_Types].xml, mk_invoice_template/_rels/.rels, mk_invoice_template/docProps/app.xml, mk_invoice_template/docProps/core.xml, mk_invoice_template/word/_rels/document.xml.rels, mk_invoice_template/word/document.xml, mk_invoice_template/word/fontTable.xml, mk_invoice_template/word/numbering.xml, mk_invoice_template/word/settings.xml, mk_invoice_template/word/styles.xml
The script prepares a generic (software engineering) invoice in Office Open XML format, using a template, and the data provided in the configuration file.
=> Add `mk_invoice` script

README.md, spell
Spell the specified phrase; supports customizable alphabets.
=> Add `spell`

README.md, plot_2y_diagram
=> Add `plot_2y_diagram` script

plot_2y_diagram
=> `plot_2y_diagram` improvements

README.md, plot_2y_diagram, plot_diagram
Although `plot_2y_diagram` can be used also for single-line diagrams, the target is slightly different (eg. output format support, for batch execution), and the code required is leaner.
=> Add `plot_diagram` script, and improve `plot_2y_diagram`

README.md
This is a lightweight approach to maintaining a changelog, while giving useful information to users seldom checking what has been recently added.
=> Add `Latest additions` section to readme

prettify
=> Add HTML support to `prettify`

encode_to_m4a
Add option for removing the source file(s).
=> encode_to_m4a: add remove source file(s) functionality

mk_invoice
Make the invoice refer the month before the previous.
Also made minor refactorings, essentially, simplifications.
=> mk_invoice: add before-previous month functionality, and minor refactorings

README.md, gitio
Generate a short GitHub URL, and copy it to the clipboard.
=> Add `gitio`

mysql_plot_diagrams
Fixes and improvements in preparation to the comparison mode.
=> Fixes and improvements to mysql_plot_diagrams

plot_diagram
Add support for files with an arbitrary number of columns.
In order to solve the ambiguity of the first column being X values or not, the `--no-x` option has been introduced.
=> plot_diagram: add support for multiple y lines

plot_diagram
Allow superposing of lines with entirely different scales, to find correlations.
Also done several refactorings and minor cosmetic fixes.
=> plot_diagram: add `auto-y-scale` functionality

mysql_collect_stats
The new option limits the number of stats (dumps) collected.
=> mysql_collect_stats: Add `--limit` functionality

plot_diagram
Besides the minor improvements, diagram fitting is now not the default anymore.
=> plot_diagram: Make diagram fitting an option, and minor/cosmetic improvements

plot_diagram
With the new support, diagrams with different scales will still be scaled, but X axis will have Y=0.
=> plot_diagram: add support for auto_y_scale without fitting

mysql_plot_diagrams
Several improvements, most notably:
- single-diagram mode: merge the diagrams of multiple directories into one
- optimizations: made merging and aggregates computation much faster
- make destination directory customizable
- store aggregates instead of printing them
=> mysql_plot_diagram: Single diagram mode, optimizations, and other improvements

mysql_plot_diagrams
An error was raised, due to missing whitespace handling.
Also made other improvements, of cosmetic nature.
=> mysql_plot_diagrams: Fix bug in aggregates computation

encode_to_m4a
Several fixes and improvements, the most important being handling of directories where the source and the destination are the same.
=> Several fixes and improvements to encode_to_m4a

mysql_collect_stats
Useful in certain circumstances, when the current user is not the user authenticating to the MySQL server.
=> mysql_collect_stats: add support for MySQL credentials

README.md, purge_trash
Handy script for purging trash files trashed before a certain threshold.
=> Add `purge_trash`

mysql_plot_diagrams
Aggregation was broken for multiple stat directories.
Also done very minor cleanups.
=> mysql_plot_diagrams: Fix aggregation bug

mysql_plot_diagrams
Add standard deviation aggregate (`stddev`).
=> mysql_plot_diagrams: Add standard deviation aggregate (`stddev`)

README.md, ft_function
Very handy script for extracting a token/line from the output of a command.
=> Add ft(_function) function/script

README.md, mylast
Convenient script that runs the last executed MySQL query, and copies the result to the clipboard.
=> Add `mylast`

README.md, texerak
Wrapper are Tesseract for conveniently OCR documents; primarily:
- handle multiple files
- convert PDFs in order to be scanned
- make language presettable
=> Add `texerak`

README.md, control_music_player
Finds one of the supported players, if running, and executes the provided action.
=> Add `control_music_player`

Gemfile, README.md, clean_recents
Clean the recent used file entries whose basename matches the specified patterns
=> Add `clean_recents`

README.md, mystart, mystop
Scripts used at the pre-FOSDEM for switching/starting MySQL versions.
=> Add `mystart`/`mystop`

mysql_collect_stats
- The password option requires no space;
- Added host option, so that it's possible to collect from remote servers;
- Minor (cosmetic) improvements.
=> mysql_collect_stats: fix password issue, and add host support

generate_wiki_home_toc
- Prettify headers
- Add `Root` header
=> Improvements to generate_wiki_toc

README.md, bedtime
Useful to avoid late-night programming :-)
=> Add `bedtime`

prettify
- Add YAML support
- Fix: the backup is done before checking the extension is supported
=> Improvements to `prettify`

gitio
Since the target is reduce space, let's do that :)
=> gitio: Strip protocol, and minor refactorings

README.md, script_template
Creates a Bash script template, and sets the permissions.
=> Add `script_template`

README.md, git_maintain_branches
Sync with upstream, if present.
A refactoring has been made (split into functions).
=> git_maintain_branches: Add sync with upstream

gitio
The protocol is not stripped anymore, however, it can now be stripped via option.
=> gitio: Add "short" functionality (protocol stripping)

encode_to_m4a
- Check destination directory
- Cosmetic improvements
=> encode_to_m4a: Minor improvements

convert_cb_archive_to_pdf
- Improve jpg files regex
- Loosen jpg fields title matcher
- Refactoring: Extract constants
- Add Thumbs.db and *.mp3 to unnecessary files
=> Improvments to convert_cb_archive_to_pdf

clean_kernel_packages, kernel_packages_maintenance/kernel_version.rb
Many improvements; in general, the script is simpler and more robust.
=> Many improvements to clean_kernel_packages

build_kernel
The pattern was not matching the libc package.
=> build_kernel: Fix packages deletion

build_kernel
- Use `--force` checkout on branch change
- Fix old files deletion (and split config/packages)
=> build_kernel improvements/fixes

build_kernel
- Fail fast when a config file is not found
- Fix RCs not excluded when searching the latest kernel version
=> build_kernel improvements

compress_dvd
Really cool! In the future, either conversion to srt, or at least subs merging, will be supported.
Required some refactorings.
=> compress_dvd: Add support for subtitles

build_kernel
Useful when working with custom branches, which also includes bisection.
Includes a minor refactoring.
=> build_kernel: Add "stay on branch" functionality

git_merge_file_commits
Fix the rewritten history; added the option to specify a subject suffix (useful when writing the version).
=> git_merge_file_commits: Fix, refactorings, and extension

build_kernel
This fixes at least one problem (transition from .0 to .1).
=> build_kernel: Normalize the versions (fix), and minor cleanups

convert_cb_archive_to_pdf
- Cosmetic improvement to `c_unnecessary_files`
- Improve filename matching
- Add support for rar extension
- Fix (unnecessary files) deletion
- Add .sfv to (unnecessary files) list
- Improvements/extensions to filename patterns
=> Improvements+fix to `convert_cb_archive_to_pdf`

desnapped
- Allow setting the binary via cmdline option
- Change sudo strategy
- Allow arbitrary operation params
=> desnapped improvement
