- README.md
- kernel_packages_maintenance/kernel_version.rb
- update_mainline_kernel
- if the latest version, build failed, try to install the previous one(s)
- add support for new `linux-modules` package
- support installation of specific patch version
> `update_mainline_kernel`: several updates

- clean_kernel_packages
- update_mainline_kernel
Allow a run without changing the system; useful mostly in the case when one wants to check what's the latest version of new kernel.
> Add dry run option to update_mainline_kernel

- clean_kernel_packages
- update_mainline_kernel
SimpleScripting::Argv's backend, OptionParser, automatically adds a short form switch for the first letter of the long form (eg. `-d` for `--dry-run`). It's not clear whether this is a bug or intentional by looking at the [documentation](https://docs.ruby-lang.org/en/2.5.0/OptionParser.html), but it's surely confusing in case where the two forms differ (eg. `-n` -> `--dry-run`).
> Rename dry run switch for kernel tools

- CHANGELOG.md
- update_mainline_kernel
HTTP addresses now redirect to HTTPS, so we use directly the latter (also avoids handling redirects).
> update_mainline_kernel: use HTTPS

- Home.md
- README.md
- generate_wiki_home_toc
Generates the `Home.md` file of a wiki repository, with a table of contents.
> Add `generate_wiki_home_toc`

- clean_kernel_packages
- Refactoring: encapsulate kernel version package matching code
- Add `modules-extra` packages to the search for packages to delete
- Remove module directories corresponding to packages removed
- On dry run, use `aptitude` in simulate mode, instead of not running it
> Improvements to clean_kernel_packages

- README.md
- connect_bt_device
Connect an audio BT device to the system.
Besides providing a mean to perform the operation, the script helps the user working around the extremely annoying issues with the steaming pile of trash that are Bluetooth, Bluez, and the Ubuntu BT support.
> Add connect_bt_device

- connect_bt_device
- fix bug where bt_device_id wasn't passed to the disconnection code
- wait for intro message when starting `bluetoothctl`
- check if device is connected, before disconnecting it
> Improvments to connect_bt_device, mainly check if device is connected, before disconnecting it

- connect_bt_device
The new support allows the user to specify a master device, in configuration where there are typically multiple master devices, and only one is required for using BT.
Other minor improvements have been done, of cosmetic nature.
> connect_bt_device: Add support for specifying a master device, and other improvements

- ejectdisk
Useful when one wants to unmount the removable disk partitions, without actually ejecting the disk, so that it can be used (eg. by a virtual machine).
> Add no-poweroff option to ejectdisk

- README.md
- winetmp
This script is a convenience for running Wine applications in a temporary, sandboxed, environment.
> Add `winetmp`

- README.md
- encode_to_m4a
Convenient script for converting music files. Uses FFmpeg with libfdk_aac (a high quality encoder).
> Add `encode_to_m4a`

- connect_bt_device
If something goes wrong (eg. neverending loop), Ctrl+C will disable the devices, resetting to (hopefully) a clean state.
> connect_bt_device: disconnect/disable the devices on interrupt

- encode_to_m4a
When a source is a directory, its content is encoded and copied into a directory, and normalized as album
Copy mode refers to:
- not encoding lossy files
- copying image files inside directories
> encode_to_m4a: add directory and copy modes

- connect_bt_device
It was broken (exit logic was broken). Also, make it two-steps: separate interruption of disconnection vs. disabling.
> connect_bt_device: interrupt handling: fix and make more granular

- git_purge_empty_branches
Add configuration, to specify branches that must never be deleted.
This has a few use cases, for example, a release branch, or cases where a certain version branch has the same HEAD as master.
> git_purge_empty_branches: add support for "protected" branches

- plot_diagram
Adds support for passing the data via stdin:
```sh
printf '1\n2\n3' | plot_diagram 
```
Also made minor improvements: to help, and better Ruby API usage for temporary files.
> plot_diagram: Add support for reading from stdin, and minor improvements

- encode_to_m4a
With this option set, files are processed in a temporary directory, instead of in-place. This helps on destinations like (GVFS) mounts on mobile devices, where file operations other than basic copy/move may fail.
Minor refactorings have also been applied, most notably, extracing the main logic blocks into functions.
> Add support for processing in a temporary directory, and minor refactorings

- plot_2y_diagram
- plot_diagram
Mad workaround - see comment in the code.
> plot*diagram: Mad workaround to wait for the diagram window to be closed before exiting

- plot_2y_diagram
- plot_diagram
Without escaping, Gnuplot interprets underscore as subscript tags.
> plot*diagram: escape titles

- mysql_plot_diagrams
For the intended use, two decimals are enough.
> mysql_plot_diagrams: Round aggregates

- mylast
Formatted EXPLAIN output generally uses `\G`, which is not in the log, so we use a heuristic to handle it.
> mylast: Clean formatted EXPLAIN output

- mylast
Fixes:
- major: if the query statements were separated by new lines, in some cases (but not all), executing the query would fail
- minor: `USE <schema>` must be added (if required) after testing for `EXPLAIN`, not before, otherwise the test would never pass
> Fix two bugs in `mylast`, and apply minor cosmetic improvements

- mylast
We don't need sed's `1d` if we specify `-N`.
> mylast: add heuristic for SHOW CREATE TABLE, and simplify header deletion

- gitio
The Perl options used were wrong. Also, simplified the regex.
> gitio: Fix (remove) trailing whitespace in resulting string

- encode_to_m4a
Parallelize the encoding of the files.
It's not clear if in theory, files could be analyzed individually for track gain, then the audio gain to be applied without recomputing, but it doesn't work based on testing:
```sh
for f in *.m4a; do aacgain -s r "$f"; done
aacgain -k -a *.m4a
```
> encode_to_m4a: Parallelize encoding of files in directories

- mystart
Allow quicker switch between versions when performing database experiments.
Undocumented not to pollute the current help, which is already quite long.
> mystart: Add create/connect to tmp schema functionality

- encode_to_m4a
After upgrading to Ubuntu 20.04, this is the reported MIME type for FLAC files.
> encode_to_m4a: Add `audo/flac` MIME type support

- bedtime
Useful for cases when the script is executed after the standby time.
> bedtime: Add poweroff-only mode

- purge_trash
Previously, it wasn't possible to discover errors when running from via GUI.
> purge_trash: Support GUI run for runtime errors notification

- convert_cb_archive_to_pdf
It hadn't been updated for `cbz`; now it's generic.
> convert_cb_archive_to_pdf: Fix output filename (remove generic `cb*` extension)

- ejectdisk
Partitions encrypted via LUKS are now unmounted (and the LUKS device locked). This has been quite tricky.
> ejectdisk: Add LUKS support

- git_rename_commits
Previously, `^` would match every line of the commit message. Now, 0777 mode is used, so it only matches the title.
> git_rename_commits: Update Perl flags (use 0777 mode)

- git_rename_commits
filter-branch requires running from the project top level.
> git_rename_commits: Automatically cd to repo top level

- ejectdisk
The newline (separator) was missing!
> ejectdisk: Fix LUKS devices handling

- download_ubuntu_packages
Very odd. On Jammy (not on Focal), opening the packages pages raises a certificate error.
> download_ubuntu_packages: Workaround SSL certificate issue on Focal (!)

- clean_kernel_packages
- kernel_packages_maintenance/kernel_version.rb
Now, orphan headers are removed.
There are also many other refactoring and improvements, also semantic (e.g. WRT supported version formats).
> clean_kernel_packages: Remove orphan headers, and several improvements

- git_find_default_branch
It's important not to produce noise, since the output of this script may be used programmatically.
> git_find_default_branch: Fix noise when running remote set-head

- build_kernel
Significant improvements in UX, and nice improvement in the code.
Along with this change, many improvements have been made, most notably:
- Remove support for RC versions
- On config import, find the latest available
- Find and use latest packaged version to decide if building or not
- Don't create the new branch if it exists already
> build_kernel: Merge functionality for with/out kernel version option (and various improvements)

- download_ubuntu_packages
There is no clean way to gather this programmatically, so we scan the daily build page.
> download_ubuntu_packages: Add support for development version

- compress_dvd
Beside the fact that the extended language is not needed, this has been done to simplify the logic. If needed, support for more tracks with the same language can be added.
> compress_dvd: Don't add extended language to the filename (removes support for more tracks with same language)

- build_kernel
When the config is downloaded, we don't need to reimport it, since the current path is the kernel local repository.
> build_kernel: Fix logic for config download
